channels:
  - bioconda
  - conda-forge

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  # DH-418, bunch of stuff fails to install if git is set higher to this e.g. git==2.47.1
  - git==2.38.1
  - jupyter-archive==3.4.0
  - jupyter-offlinenotebook==0.3.1
  - jupyter-resource-usage==1.1.1
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.16.0
  - jupyterhub==5.3.0
  - jupyterlab==4.4.4
  - jupyterlab-git==0.51.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.4.4
  - otter-grader==6.1.3
  - pip==25.1.1
  - python==3.11.*

  # Package to allow Jupyter Notebook or JupyterLab applications in one conda env to access other kernels (e.g. qiime2)
  - nb_conda_kernels==2.5.1
  - jupyter-rsession-proxy==2.3.0

  # Packages from bioconda for IB134L
  - augustus==3.5.0
  - bcftools==1.16
  - blast==2.16.0
  - bwa==0.7.18
  - emboss==6.6.0
  - fastqc==0.11.9
  - hisat2==2.2.1
  - mafft==7.471
  - paml==4.9
  - plink==1.90b6.21
  - phyml==3.3.20200621
  - raxml-ng==1.0.1
  - samtools==1.3.1
  - seqtk==1.4
  - sra-tools==2.11
  - structure==2.3.4
  - subread==2.0.6
  - syncthing==1.29.7
  - trimmomatic==0.39

  # Packages for IB120/201/CCB210
  - sympy==1.14.0

  # Packages from bioconda for BioE-131, Fall 2020, Issue #1885
  - bowtie2==2.5.4
  - spades==3.14.1

  # Packages for MCB280A, Spring 2022
  - bedtools==2.31.1

  # Packages from bioconda for BIO1B
  - dendropy==4.4.0
  - muscle==3.8.1551
  - raxml==8.2.13

  # pedagogy packages
  - pandas==2.3.0
  - scipy==1.16.0
  - seaborn==0.13.2

  # compbio BioE c146, Fall 22 and into the future, issue 3785
  - scikit-learn==1.7.0

  # bug w/notebook and traitlets: https://github.com/jupyter/notebook/issues/7048
  - traitlets==5.14.3

  # for MCELLBI201B (FA24) https://github.com/berkeley-dsep-infra/datahub/issues/5988
  - macs2==2.2.9.1
  
  # For https://github.com/berkeley-dsep-infra/datahub/issues/1846
  # Conda does not have these
  - pip:
  # MCB280A, Spring 2022
    - geonomics==1.4.1
    - nlmpy==1.2.0
    - pybedtools==0.12.0
  # Packages for MCB-160L iss #3942
    # DH-418 requires pandas 1.5.3, conflicts with otter-grader which needs 2.2.2
    # For https://github.com/berkeley-dsep-infra/datahub/issues/7575
    - allensdk==2.16.2
  # required for basic functionality
    - git-credential-helpers==0.2
    - nbconvert[webpdf]==7.16.6
    - nb2pdf==0.6.2
    - nbpdfexport==0.2.1
  # DH - 557 
    - datascience==0.18.0
